Created a token_endpoint variable in the config file
tarickb/sasl-xoauth2 pull request #5
Opened 2020-10-20 22:31 UTC by tparkercbn

To allow the configuratioin of alternative token endpoints

2020-10-21 02:15 UTC, tarickb commented
Hey, thanks for doing this! Overall I think the change looks good, I'm just wondering if the documentation would be simpler if you omitted `token_endpoint` in the examples (because the default is fine for Gmail, which most of the doc focuses on) and instead wrote up a section on how to use this plugin with Office365? There you could detail how to get a client ID, what the right endpoint would be, and any other Office365 specifics. How does that sound?

(Also, have you signed a [contributor license agreement](https://github.com/tarickb/sasl-xoauth2/blob/master/CONTRIBUTING.md)?)

2020-10-21 04:34 UTC, tparkercbn commented
Hi.  That’s a good idea to omit it.  My first version of this commit didn’t have a default set (I hadn’t figured out how to set it yet) so it was a mandatory field.

Once we get it working properly with O365 I’ll write it up and submit a pull request for a readme update.  Microsoft is not making this easy at all.

I have not signed the contributor agreement yet but I will tomorrow.

Tom

From: tarickb <notifications@github.com>
Sent: October 20, 2020 8:16 PM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


Hey, thanks for doing this! Overall I think the change looks good, I'm just wondering if the documentation would be simpler if you omitted token_endpoint in the examples (because the default is fine for Gmail, which most of the doc focuses on) and instead wrote up a section on how to use this plugin with Office365? There you could detail how to get a client ID, what the right endpoint would be, and any other Office365 specifics. How does that sound?

(Also, have you signed a contributor license agreement<https://github.com/tarickb/sasl-xoauth2/blob/master/CONTRIBUTING.md>?)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#issuecomment-713248127>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5SWZMPYG6GLDE65QJTSLY74HANCNFSM4SY6ZKFQ>.

2020-10-21 15:44 UTC, tparkercbn commented
Good morning.  I have signed the agreement now from my personal account (vagabond@tomparker.ca<mailto:vagabond@tomparker.ca>) with my github username.

I found a bug that I’m not sure how to fix in my commit.  (I’m not a C developer at all) that maybe you can help me with.

I added a logging statement in token_store.cc on line 86 to log out which server we are using (mostly to debug) and I’m getting garbage from my call to Config::Get()->token_endpoint.

It seems to work using the same code below in the HttpPost call because I can see the request being generated.

Any help would be appreciated.

Tom

From: tarickb <notifications@github.com>
Sent: October 20, 2020 8:16 PM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


Hey, thanks for doing this! Overall I think the change looks good, I'm just wondering if the documentation would be simpler if you omitted token_endpoint in the examples (because the default is fine for Gmail, which most of the doc focuses on) and instead wrote up a section on how to use this plugin with Office365? There you could detail how to get a client ID, what the right endpoint would be, and any other Office365 specifics. How does that sound?

(Also, have you signed a contributor license agreement<https://github.com/tarickb/sasl-xoauth2/blob/master/CONTRIBUTING.md>?)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#issuecomment-713248127>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5SWZMPYG6GLDE65QJTSLY74HANCNFSM4SY6ZKFQ>.

2020-10-21 23:13 UTC, tarickb commented on src/token_store.cc
> +  log_->Write("TokenStore::Refresh: token_endpoint: %s", Config::Get()->token_endpoint());
%s in the format string expects a char*, so you'll need "Config::Get()->token_endpoint().c_str()" instead.

2020-10-21 23:15 UTC, tarickb commented
Thanks for taking care of the agreement! The reason you're seeing garbage is a missing c_str() call (I left a comment) -- sorry I didn't catch that the first time I looked at your commit.

2020-10-21 23:16 UTC, tparkercbn commented
Thanks!  These are the little details that I have no idea about 😊

I will fix and resubmit my pull request.  We are making progress on getting the toke ns we need from O365 but we are getting an odd “Could not resolve host” error when we definitely can (same host works on the command line from curl).  Have you ever run into that?

From: tarickb <notifications@github.com>
Sent: October 21, 2020 5:14 PM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


@tarickb commented on this pull request.

________________________________

In src/token_store.cc<https://github.com/tarickb/sasl-xoauth2/pull/5#discussion_r509787737>:

> @@ -85,11 +83,12 @@ int TokenStore::Refresh() {

       "&grant_type=refresh_token&refresh_token=" + refresh_;

   std::string response;

   long response_code = 0;

+  log_->Write("TokenStore::Refresh: token_endpoint: %s", Config::Get()->token_endpoint());

%s in the format string expects a char*, so you'll need "Config::Get()->token_endpoint().c_str()" instead.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#pullrequestreview-514253845>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5VXKFGX256D3MAHZBLSL5TLRANCNFSM4SY6ZKFQ>.

2020-10-21 23:26 UTC, tarickb commented
Hmm, the only thing that immediately comes to mind is that maybe you're on an IPv6-only system? I can imagine curl on the command line figuring that out and behaving appropriately, whereas I may well have forgotten to set some parameters somewhere to enable IPv6 within the plugin...

2020-10-21 23:28 UTC, tparkercbn commented
No.  We are on an IPv4 system.  But that brings up an interesting point.  I think DNS may be resolving AAAA records… and trying to use IPv6 in sasl.  I saw an IPv6 Ip in the logs.  Let me debug that a bit on my side

Thanks

From: tarickb <notifications@github.com>
Sent: October 21, 2020 5:27 PM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


Hmm, the only thing that immediately comes to mind is that maybe you're on an IPv6-only system? I can imagine curl on the command line figuring that out and behaving appropriately, whereas I may well have forgotten to set some parameters somewhere to enable IPv6 within the plugin...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#issuecomment-713972095>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5VGAY3TFWXHESIB3LTSL5U2ZANCNFSM4SY6ZKFQ>.

2020-10-28 14:52 UTC, tarickb commented
Any luck with the v4/v6 debugging?

2020-10-28 14:56 UTC, tparkercbn commented
Good morning.

Not yet but the primary dev on it is my co-op student (I got pulled into a different project for a few weeks) and he is a little lost when it comes to this stuff.

It is still a very odd error.  The system is able to ping and curl the URL from the cli, but not from inside saslauthd/the the oath plugin.

Tom

From: tarickb <notifications@github.com>
Sent: October 28, 2020 8:53 AM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


Any luck with the v4/v6 debugging?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#issuecomment-717986822>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5WLU62HDEKXXUH32JDSNAV3ZANCNFSM4SY6ZKFQ>.

2020-10-28 15:22 UTC, tarickb commented
Well, whenever you (or your co-op student) get around to it, try [this patch](https://gist.github.com/tarickb/efdb09f42460cf53e1c6f7b8538d8af6). It adds a config file (`/etc/sasl-xoauth2.conf`) option, `force_ipv4`, that if set to `yes` instructs libcurl to use IPv4 addresses if DNS resolution results in both v4 and v6 addresses.

2020-10-28 16:23 UTC, tparkercbn commented
Thanks!  I’ll get him a new copy of the library with this patch included.

Tom

From: tarickb <notifications@github.com>
Sent: October 28, 2020 9:22 AM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


Well, whenever you (or your co-op student) get around to it, try this patch<https://gist.github.com/tarickb/efdb09f42460cf53e1c6f7b8538d8af6>. It adds a config file (/etc/sasl-xoauth2.conf) option, force_ipv4, that if set to yes instructs libcurl to use IPv4 addresses if DNS resolution results in both v4 and v6 addresses.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#issuecomment-718007200>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5SLPVB4ETBV3VIPVZLSNAZKZANCNFSM4SY6ZKFQ>.

2020-10-29 16:56 UTC, tparkercbn commented
Good morning.

I have applied your patch and rebuilt and we are still getting the odd Could not resolve host.

SELinux is off, the host can be hit from a browser and from the command line but for some reason not from sasl-xoath2

Tom

Oct 29 12:12:07 localhost sasl-xoauth2[9744]:  2020-10-29 12:12:07: TokenStore::Refresh: http error: Could not resolve host: login.microsoftonline.com
Oct 29 12:12:07 localhost sasl-xoauth2[9744]:  2020-10-29 12:12:07: Client::DoStep: new state 0 and err -5
Oct 29 12:12:07 localhost sasl-xoauth2[9744]:  2020-10-29 12:12:07: Client: destroyed
Oct 29 12:12:07 localhost sasl-xoauth2[9742]: auth failed:
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: Client: created
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: Client::DoStep: called with state 0
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: Client::InitialStep: TriggerAuthNameCallback err=0
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: Client::InitialStep: TriggerPasswordCallback err=0
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: TokenStore::Read: file=/etc/tokens/karl_rez@outlook.com<mailto:file=/etc/tokens/karl_rez@outlook.com>
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: TokenStore::Read: refresh=0.AAAAH1Ai-LwYYkukVScMQXND2C1ijjTTA8xLs6iO5gvTwPZ2AAk.AgABAAAAAAB2UyzwtQEKR7-rWbgdcBZIAQDs_wIA9P_QLPPzBbnBscwB_Vt-7jL8Y25vzdLlKtLnfqlzi4_aZm1ppivbk4Tqd1gr7rbIwh5ygcgO1O--qqoU01kqjKgB2CtPeGv-rFuDsxATjsdO1QGAcgw68Kj5ef8-C18hWxdDIRbqvMqd7z51ijkGl-ssx7FecWi-fI4Z83xkhhA4_GoGtLDHmUFCax2MyK63RZZp1CkK0PIKM5P4oRSt7s6NHPjpSEhWYWZSFeHxLanIRKGedDwdcyhfHiENrie1GUwoeHADSHdAljC3f6Bv3Fwb1ZO6ZlFSzieyklWOwUwlR6aFrrUQoAhxFMuXJgK_BFDCnOmyPIj7MFf11j_QjYAx9qJiF86nQS8FYCPFb7tpqUoyWbnpqMqUiIBtadQg1ucRFz-Nw9t2fqO8ayWACDMxfU1tARhGsKdOAa57FDWSPDfHzM2h4hatd68SbbQssIawRlQO-hO3QeeywvQ4O3_QvUGKPkBzuD8UqVXNQZybwvuwqvQAxrb2xVTRkk0ayCzFU0iSfnISpkplpeEdL57Fdthm0SiKmPtqLttl8s5ejknW06-5ELsjI_VDwmAZOmUxl7B7t4XGixRTWe9VhsGcvHt-8y7R5qX2JRYpLYKC1GsvfQGxgdFgiJjOeJlOF6XbmHeAhzcqFW1vVKKVJjf9NnAyuVEZ0op7V-S9KtxxpL-ybdsUnW8s6UAHD1vcbekBxIXZbFk7E_XozK5PBl7jXilR508Ub5STFR4juX655B4eSSAbLvhp6IxTxcrxl03FTt-IuT60BSoRj1Ycx9X09rQwy-n9LBoWvVmmJuh9tyBbH9wGbtBcm16YlZFilmtQvU3rsg9bLJpU43GBhgJULJ2sljhbjMXXoD0A5-gsqCu7w8eyu2X0GrpUkYhFAA, acc
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: TokenStore::GetAccessToken: token expired. refreshing.
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: TokenStore::Refresh: attempt 1
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: TokenStore::Refresh: request: client_id=348e622d-03d3-4bcc-b3a8-8ee60bd3c0f6&client_secret=1aI2-MH7Wna~9B~9yVY3_mn4WQ7-.Tq75y&grant_type=refresh_token&refresh_token=0.AAAAH1Ai-LwYYkukVScMQXND2C1ijjTTA8xLs6iO5gvTwPZ2AAk.AgABAAAAAAB2UyzwtQEKR7-rWbgdcBZIAQDs_wIA9P_QLPPzBbnBscwB_Vt-7jL8Y25vzdLlKtLnfqlzi4_aZm1ppivbk4Tqd1gr7rbIwh5ygcgO1O--qqoU01kqjKgB2CtPeGv-rFuDsxATjsdO1QGAcgw68Kj5ef8-C18hWxdDIRbqvMqd7z51ijkGl-ssx7FecWi-fI4Z83xkhhA4_GoGtLDHmUFCax2MyK63RZZp1CkK0PIKM5P4oRSt7s6NHPjpSEhWYWZSFeHxLanIRKGedDwdcyhfHiENrie1GUwoeHADSHdAljC3f6Bv3Fwb1ZO6ZlFSzieyklWOwUwlR6aFrrUQoAhxFMuXJgK_BFDCnOmyPIj7MFf11j_QjYAx9qJiF86nQS8FYCPFb7tpqUoyWbnpqMqUiIBtadQg1ucRFz-Nw9t2fqO8ayWACDMxfU1tARhGsKdOAa57FDWSPDfHzM2h4hatd68SbbQssIawRlQO-hO3QeeywvQ4O3_QvUGKPkBzuD8UqVXNQZybwvuwqvQAxrb2xVTRkk0ayCzFU0iSfnISpkplpeEdL57Fdthm0SiKmPtqLttl8s5ejknW06-5ELsjI_VDwmAZOmUxl7B7t4XGixRTWe9VhsGcvHt-8y7R5qX2JRYpLYKC1GsvfQGxgdFgiJjOeJlOF6XbmHeAhzcqFW1vVKKVJjf9NnAyuVEZ0op7V-S9KtxxpL-ybdsUnW8s6UAHD1vcbekBxIXZbFk7E_XozK5PBl7jXilR508Ub5STFR4juX655B4eSSAbLvhp6IxT
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: TokenStore::Refresh: http error: Could not resolve host: login.microsoftonline.com
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: Client::DoStep: new state 0 and err -5
Oct 29 12:12:07 localhost sasl-xoauth2[9742]:  2020-10-29 12:12:07: Client: destroyed



From: tarickb <notifications@github.com>
Sent: October 28, 2020 9:22 AM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


Well, whenever you (or your co-op student) get around to it, try this patch<https://gist.github.com/tarickb/efdb09f42460cf53e1c6f7b8538d8af6>. It adds a config file (/etc/sasl-xoauth2.conf) option, force_ipv4, that if set to yes instructs libcurl to use IPv4 addresses if DNS resolution results in both v4 and v6 addresses.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#issuecomment-718007200>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5SLPVB4ETBV3VIPVZLSNAZKZANCNFSM4SY6ZKFQ>.

2020-10-29 18:50 UTC, tarickb commented
Couple follow-up questions:

* What libcurl package are you using? What's the output of `dpkg-query -l | grep libcurl`?
* Dumb question, but did you set `"force_ipv4": "yes"` in `/etc/sasl-xoauth2.conf`?

2020-10-29 22:33 UTC, tparkercbn commented
*   Libcurl-7.61.1-12.el8.x86_64
  *   And the force_ipv4 variable is set to “yes”


Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: tarickb <notifications@github.com>
Sent: Thursday, October 29, 2020 12:50:24 PM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


Couple follow-up questions:

  *   What libcurl package are you using? What's the output of dpkg-query -l | grep libcurl?
  *   Dumb question, but did you set "force_ipv4": "yes" in /etc/sasl-xoauth2.conf?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#issuecomment-718951822>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5TVWAOG2A32O6KWJ63SNG2PBANCNFSM4SY6ZKFQ>.

2020-10-29 22:57 UTC, tarickb commented
I wonder if you're bumping into some chroot issues? Do you have a `resolv.conf` file in `/var/spool/postfix/etc`? You'll probably need something there that matches whatever's in `/etc`, along with possibly `host.conf` and `nsswitch.conf`.

2020-11-06 18:14 UTC, tparkercbn commented
Hello,

I am the student working with tparkercbn  on trying to get an Office365 implementation of your plugin. I am currently receiving "535 5.7.3 Authentication unsuccessful" from the outlook server which I am trying to debug.

I included two screenshots which show I think part of our token is being cut off. Do you think that is my issue? I also included a file with what I am getting in the journal as maybe I need to configure something else differently on my end.

Appreciate your help.
Thanks,

Karl

[12:54, 2020-11-06] karl: Nov 06 12:49:58 localhost.localdomain postfix/smtp[13368]: smtp_sasl_passwd_lookup: host `smtp.outlook.com' user `karl_rez@outlook.com' pass `/etc/tokens/karl_rez@outlook.com'
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13368]: starting new SASL client
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13368]: name_mask: noanonymous
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13368]: smtp_sasl_authenticate: smtp.outlook.com[2603:1036:c00:1::2]:587: SASL mechanisms XOAUTH2
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13368]: xsasl_cyrus_client_get_user: karl_rez@outlook.com
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13368]: xsasl_cyrus_client_get_passwd: /etc/tokens/karl_rez@outlook.com
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13368]: xsasl_cyrus_client_first: uncoded initial reply: user=karl_rez@outlook.com\001auth=Bearer eyJ0eXAiOiJKV1QiLCJub25jZSI6InpTLVVwVmV1VHJtNXRmcTdaUmI2TkhZMWp3UjhIa2VPYmtqNU9JQ21yWXMiLCJhbGciOiJSUzI1NiIsIng1dCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCIsImtpZCI6ImtnMkxZczJUMENUaklmajRydDZKSXluZW4zOCJ9.eyJhdWQiOiJodHRwczovL2dyYXBoLm1pY3Jvc29mdC5jb20iLCJpc3MiOiJodHRwczovL3N0cy53aW5kb3dzLm5ldC9mMjlmZDI3Mi1hYzc3LTQ1NzAtOWQzMC1iYTU4NjlmZTk4NzIvIiwiaWF0IjoxNjA0NjgyNDA2LCJuYmYiOjE2MDQ2ODI0MDYsImV4cCI6MTYwNDY4NjMwNiwiYWNjdCI6MCwiYWNyIjoiMSIsImFpbyI6IkUyUmdZTkNQV3ZMNXEraGZhNmVhS1FJQjNPN0JDK1FMLys1ZHNaMjVZcmY0eFp6NGpaNEEiLCJhbXIiOlsicHdkIl0sImFwcF9kaXNwbGF5bmFtZSI6InBvc3RmaXgiLCJhcHBpZCI6IjQzODM0NDA3LWUyN2ItNDE5Ni05M2MyLTBlNmU5ODgyOWE2MiIsImFwcGlkYWNyIjoiMSIsImZhbWlseV9uYW1lIjoicmV6YW5zb2ZmIiwiZ2l2ZW5fbmFtZSI6ImthcmwiLCJpZHR5cCI6InVzZXIiLCJpcGFkZHIiOiIxNzQuMTE2LjExLjIxIiwibmFtZSI6ImthcmwiLCJvaWQiOiI4ZWM3MzM1MS1jM2FjLTRkMDgtODVhYS04NWIwZWZhM2NhN2IiLCJwbGF0ZiI6IjE0IiwicHVpZCI6IjEwMDMyMDAwRjM5RUYzRjYiLCJyaCI6IjAuQUFBQWN0S2Y4bmVzY0VXZE1McFlhZjZZY2dkRWcwTjc0cFpCazhJT2JwaUNtbUoxQU5zLiIsInNjcCI6ImVtYWlsIE1haWwuUmVhZFdyaXRlIE1haWwuUmVhZFdyaXRlLlNoYXJlZCBNYWlsLlNlbmQgTWFpbC5TZW5kLlNoYXJlZCBvZmZsaW5lX2FjY2VzcyBvcGVuaWQgcHJvZmlsZSBTTVRQLlNlbmQgVXNlci5SZWFkIFVzZXIuUmVhZFdyaXRlLkFsbCIsInN1YiI6IkZjajU2Q1NNLURObDhrVmdtTDZUT0lxTzBkdkVaZzNuandzcmJOYllIYnciLCJ0ZW5hbnRfcmVnaW9uX3Njb3BlIjoiTkEiLCJ0aWQiOiJmMjlmZDI3Mi1hYzc3LTQ1NzAtOWQzMC1iYTU4NjlmZTk4NzIiLCJ1bmlxdWVfbmFtZSI6ImthcmxfcmV6X291dGxvb2suY29tI0VYVCNAa2FybHNvcmcub25taWNyb3NvZnQuY29tIiwidXBuIjoia2FybF9yZXpfb3V0bG9vay5jb20jRVhUI0BrYXJsc29yZy5vbm1pY3Jvc29mdC5jb20iLCJ1dGkiOiI4UmNqSHY2amVrS1FQeFkzM0JNRUFRIiwidmVyIjoiMS4wIiwid2lkcyI6WyI2MmU5MDM5NC02OWY1LTQyMzctOTE5MC0wMTIxNzcxNDVlMTAiLCJiNzlmYmY0ZC0zZWY5LTQ2ODktODE0My03NmIxOTRlODU1MDkiXSwieG1zX3RjZHQiOjE2MDQzNjE0NTF9.DB08q8yZdlHW3KySmwcBINJ7nxy0otnFmyJ0JpUIJhvCpgl2McXO9cUZQ7eWjvIW6hfbqGT_vMMilSJumxbY5-U9gcN7GJRCRbKEqfMjPrhS1a97M-kmO4Oo7LgIZ6xLZ7LQTOKtyyrIxVr5zwrR8xexWkWede6EdZwdIGXxonoaWi781gfwvwJFphgR
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13368]: > smtp.outlook.com[2603:1036:c00:1::2]:587: AUTH XOAUTH2 dXNlcj1rYXJsX3JlekBvdXRsb29rLmNvbQFhdXRoPUJlYXJlciBleUowZVhBaU9pSktWMVFpTENKdWIyNWpaU0k2SW5wVExWVndWbVYxVkhKdE5YUm1jVGRhVW1JMlRraFpNV3AzVWpoSWEyVlBZbXRxTlU5SlEyMXlXWE1pTENKaGJHY2lPaUpTVXpJMU5pSXNJbmcxZENJNkltdG5Na3haY3pKVU1FTlVha2xtYWpSeWREWktTWGx1Wlc0ek9DSXNJbXRwWkNJNkltdG5Na3haY3pKVU1FTlVha2xtYWpSeWREWktTWGx1Wlc0ek9DSjkuZXlKaGRXUWlPaUpvZEhSd2N6b3ZMMmR5WVhCb0xtMXBZM0p2YzI5bWRDNWpiMjBpTENKcGMzTWlPaUpvZEhSd2N6b3ZMM04wY3k1M2FXNWtiM2R6TG01bGRDOW1NamxtWkRJM01pMWhZemMzTFRRMU56QXRPV1F6TUMxaVlUVTROamxtWlRrNE56SXZJaXdpYVdGMElqb3hOakEwTmpneU5EQTJMQ0p1WW1ZaU9qRTJNRFEyT0RJME1EWXNJbVY0Y0NJNk1UWXdORFk0TmpNd05pd2lZV05qZENJNk1Dd2lZV055SWpvaU1TSXNJbUZwYnlJNklrVXlVbWRaVGtOUVYzWk1OWEVyYUdaaE5tVmhTMUZKUWpOUE4wSkRLMUZNTHlzMVpITmFNalZaY21ZMGVGcDZOR3BhTkVFaUxDSmhiWElpT2xzaWNIZGtJbDBzSW1Gd2NGOWthWE53YkdGNWJtRnRaU0k2SW5CdmMzUm1hWGdpTENKaGNIQnBaQ0k2SWpRek9ETTBOREEzTFdVeU4ySXROREU1TmkwNU0yTXlMVEJsTm1VNU9EZ3lPV0UyTWlJc0ltRndjR2xrWVdOeUlqb2lNU0lzSW1aaGJXbHNlVjl1WVcxbElqb2ljbVY2WVc1emIyWm1JaXdpWjJsMlpXNWZibUZ0WlNJNkltdGhjbXdpTENKcFpIUjVjQ0k2SW5WelpYSWlMQ0pwY0dGa1pISWlPaUl4TnpRdU1URTJMakV4TGpJeElpd2libUZ0WlNJNkltdGhjbXdpTENKdmFXUWlPaUk0WldNM016TTFNUzFqTTJGakxUUmtNRGd0T0RWaFlTMDROV0l3WldaaE0yTmhOMklpTENKd2JHRjBaaUk2SWpFMElpd2ljSFZwWkNJNklqRXdNRE15TURBd1JqTTVSVVl6UmpZaUxDSnlhQ0k2SWpBdVFVRkJRV04wUzJZNGJtVnpZMFZYWkUxTWNGbGhaalpaWTJka1JXY3dUamMwY0ZwQ2F6aEpUMkp3YVVOdGJVb3hRVTV6TGlJc0luTmpjQ0k2SW1WdFlXbHNJRTFoYVd3dVVtVmhaRmR5YVhSbElFMWhhV3d1VW1WaFpGZHlhWFJsTGxOb1lYSmxaQ0JOWVdsc0xsTmxibVFnVFdGcGJDNVRaVzVrTGxOb1lYSmxaQ0J2Wm1ac2FXNWxYMkZqWTJWemN5QnZjR1Z1YVdRZ2NISnZabWxzWlNCVFRWUlFMbE5sYm1RZ1ZYTmxjaTVTWldGa0lGVnpaWEl1VW1WaFpGZHlhWFJsTGtGc2JDSXNJbk4xWWlJNklrWmphalUyUTFOTkxVUk9iRGhyVm1kdFREWlVUMGx4VHpCa2RrVmFaek51YW5kemNtSk9ZbGxJWW5jaUxDSjBaVzVoYm5SZmNtVm5hVzl1WDNOamIzQmxJam9pVGtFaUxDSjBhV1FpT2lKbU1qbG1aREkzTWkxaFl6YzNMVFExTnpBdE9XUXpNQzFpWVRVNE5qbG1aVGs0TnpJaUxDSjFibWx4ZFdWZmJtRnRaU0k2SW10aGNteGZjbVY2WDI5MWRHeHZiMnN1WTI5dEkwVllWQ05BYTJGeWJITnZjbWN1YjI
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13368]: vstream_fflush_some: fd 22 flush 2823
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: vstream_buf_get_ready: fd 22 got 83
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: < smtp.outlook.com[2603:1036:c00:1::2]:587: 535 5.7.3 Authentication unsuccessful [YTXPR0101CA0057.CANPRD01.PROD.OUTLOOK.COM]
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: 70A7A60A0984: SASL authentication failed; server smtp.outlook.com[2603:1036:c00:1::2] said: 535 5.7.3 Authentication unsuccessful [YTXPR0101CA0057.CANPRD01.PROD.OUTLOOK.COM]
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: smtp_stream_setup: maxtime=300 enable_deadline=0
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: > smtp.outlook.com[2603:1036:c00:1::2]:587: QUIT
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: name_mask: resource
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: name_mask: software
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: vstream_fflush_some: fd 22 flush 6
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: vstream_fflush_some: fd 22 flush 0
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: disposing SASL state information
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: ctable_locate: leave existing entry key W3NtdHAub3V0bG9vay5jb21dOjU4Nw==:smtp.outlook.com:587:
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: smtp_connect_addr: trying: smtp.outlook.com[52.96.88.210] port 587...
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: vstream_tweak_tcp: TCP_MAXSEG 1460
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: match_hostname: debug_peer_list: smtp.outlook.com ~? 127.0.0.1
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: match_hostaddr: debug_peer_list: 52.96.88.210 ~? 127.0.0.1
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: match_hostname: debug_peer_list: smtp.outlook.com ~? outlook.com
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: smtp_stream_setup: maxtime=300 enable_deadline=0
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: vstream_buf_get_ready: fd 22 got 110
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: < smtp.outlook.com[52.96.88.210]:587: 220 YT1PR01CA0061.outlook.office365.com Microsoft ESMTP MAIL Service ready at Fri, 6 Nov 2020 17:49:
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: > smtp.outlook.com[52.96.88.210]:587: EHLO localhost.localdomain
Nov 06 12:49:58 localhost.localdomain postfix/smtp[13367]: vstream_fflush_some: fd 22 flush  [...]

2020-11-07 07:35 UTC, tarickb commented
So I dug into this a little and after a lot of futzing with OAuth2, managed to get my local Postfix instance to send mail via Outlook. At least now we know it's possible. :)

A few ideas/questions:

1. Do you have `log_full_trace_on_failure` set to `yes` in your config file? In the future it'd be useful to also get whatever sasl-xoauth2 is sending to syslog -- those messages tend to be more useful than the SMTP blow-by-blow that Postfix provides.
1. What's the token endpoint you're using? I found that for my regular Outlook account I had to use `https://login.microsoftonline.com/consumers/oauth2/v2.0/token`. My understanding after reading [some Microsoft documentation](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints) is that you may need to replace `consumers` with `common`, depending on what environment you're in.
1. How are you generating your initial tokens? By this I mean the access and refresh tokens that you'd put in `/var/spool/postfix/etc/tokens/foo@bar.com`. I found this to be a little tricky myself and ended up writing a script to automate it. I'll try to clean it up and commit it.
1. Did you grant `SMTP.Send` permission to the Azure app you had to create to get a client ID?

(Also, just FYI, you probably want to redact tokens and whatnot from logs when you post them somewhere public. I think even these short-lived tokens are still valid for ~one hour.)

2020-11-09 17:50 UTC, tparkercbn commented
1.  Yes, I have log_full_trace_failure set to yes.
  2.  I was using https://login.microsoftonline.com/common/oauth2/token, I tried adding /v2.0 and and tried with /consumer but didn’t have any luck.
  3.  To generate the tokens I am just using curl on the command line and pasting the token response into my token file.



My request looks like this:

curl -X POST -d 'grant_type=password&client_id={client id}&client_secret={client secret}&resource=https://graph.microsoft.com&username=karl@karlsorg.onmicrosoft.com&password={password} &scope=offline_access%20user.read%20mail.read%smtp.send' https://login.microsoftonline.com/{tenant<https://login.microsoftonline.com/%7btenant> id}/oauth2/token



And receive this token:

{"token_type":"Bearer","scope":"email Mail.ReadWrite Mail.ReadWrite.Shared Mail.Send Mail.Send.Shared offline_access openid profile SMTP.Send User.Read User.ReadWrite.All","expires_in":"3599","ext_expires_in":"3599","expires_on":"1604943840","not_before":"1604939940","resource":"https://graph.microsoft.com","access_token":" {access token}","refresh_token":"{refresh token}"}



I am thinking I may need to fix my setup in Azure, as I am a bit unsure on what I am doing here. What I did was create an application for Postfix in Azure and then created a user  assigned to the application who gets the access and refresh token. If you had a simpler solution where I could just use a personal email instead of a assigned user, I would love to hear that.



  1.  Yes, I did grant the SMTP.Send permission for the app.


From: tarickb <notifications@github.com>
Sent: November 7, 2020 1:36 AM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


So I dug into this a little and after a lot of futzing with OAuth2, managed to get my local Postfix instance to send mail via Outlook. At least now we know it's possible. :)

A few ideas/questions:

  1.  Do you have log_full_trace_on_failure set to yes in your config file? In the future it'd be useful to also get whatever sasl-xoauth2 is sending to syslog -- those messages tend to be more useful than the SMTP blow-by-blow that Postfix provides.
  2.  What's the token endpoint you're using? I found that for my regular Outlook account I had to use https://login.microsoftonline.com/consumers/oauth2/v2.0/token. My understanding after reading some Microsoft documentation<https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols#endpoints> is that you may need to replace consumers with common, depending on what environment you're in.
  3.  How are you generating your initial tokens? By this I mean the access and refresh tokens that you'd put in /var/spool/postfix/etc/tokens/foo@bar.com<mailto:/var/spool/postfix/etc/tokens/foo@bar.com>. I found this to be a little tricky myself and ended up writing a script to automate it. I'll try to clean it up and commit it.
  4.  Did you grant SMTP.Send permission to the Azure app you had to create to get a client ID?

(Also, just FYI, you probably want to redact tokens and whatnot from logs when you post them somewhere public. I think even these short-lived tokens are still valid for ~one hour.)

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#issuecomment-723413264>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5QU34LVBVEUVB3ZQFLSOT2EZANCNFSM4SY6ZKFQ>.

2020-11-09 18:11 UTC, tarickb commented
If you have `log_full_trace_on_failure` set to `yes` then you should see a bunch of messages in syslog from sasl-xoauth2 itself. Could you send them over? `zgrep sasl-xoauth2 /var/log/syslog*` ought to do it, assuming your system writes to `/var/log/syslog`.

2020-11-09 19:55 UTC, karlrez commented
I do have the log_full_trace_on_failure set to `yes` and I did get this message when I changed my token endpoint to match yours:

Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: Client: created
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: Client::DoStep: called with state 0
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: Client::InitialStep: TriggerAuthNameCallback err=0
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: Client::InitialStep: TriggerPasswordCallback err=0
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: TokenStore::Read: file=/etc/tokens/karl_rez@outlook.com
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: TokenStore::Read: refresh=0.AAAActKf8nescEWdMLpYaf6YcgdEg0N74pZBk8IObpiCmmJ1AGs.AgABAAAAAAB2UyzwtQEKR7-rWbgdcBZIAQDs_wIA9P8N92raIi1UOQ895yBHkL_QcBF-Mw8kuSWnPDOkouf6Pr7ZMMQNd_4MQXFfuNtD_hU_MksXPxcgDXiOdFXvs4ylLLBY2hRE_--cSaiYwSWb_QNFnqFjo92AmPy1_ZsdVHpZWAP8Zq5f4Q7IWgQfMSMIbS5lqQHehtP005KIOH8WyXnrkHd9XJjI0H-ZNW3CcXt3-deUnxmG1qJNwkIVpRMv6fRjO0L3tUKPPs9xT_BXx2RJnQ8G_3Du-Zzd6-gxqG2vidtTg78gr3WeA_snhLQNIEhLNuM9SyLdlUgnazVhIq-oKPdzU2Hhmkrh4KqDdTpp92zq7WmnP2ek4-Cr37zjc2Wz7Lc7e31-tnz8EgNTICaHRdgw5OBnauiwPIkHeKdQHRqFPF2am_V64RAFXqqWbubb11YwPTpS_8M49FMCh_Rym0OvrMwids9eDYvvNmrJf151cQ5M2ZWg7SQUzQrhT8D6YsCgRCFwR2JXZYBuCLE1LZPzxRRLkTllQCUU5CcPHC6rlGTJhL4FzSlTCzDScUFA8jpQB1KBLXsxOX2Ue5Cgp24qyEXiIizmGsLASfetG_Aqqmn03ZEfAPd6paYXqGXOZdnk6TLn9QleeWwfSuEIC8N3soW3oDAfbRV5fkzEIW9IoGVcA4CoJavHuGrbNgmDzuTIXF-b9sWT8zAXGfBW1FiFmYifI0tImHv08EaxLw478yn3WE1rQaVXxdZMdoJpLz59BmfshyTBF_0-cGhLZY84U0I5m7IC-RdET7GssWc5I7C_2RKX8jaFZM6rqkFtD9SjTKv_zgWo50Y06ZGsKBOEzxi8FxyFCJgsMOYp7uFsiUIQpMrDhota4AzdzW917wdvVD0lscA, access=eyJ0eXAiOiJKV1QiLCJub25
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: TokenStore::GetAccessToken: token expired. refreshing.
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: TokenStore::Refresh: attempt 1
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: TokenStore::Refresh: request: client_id=43834407-e27b-4196-93c2-0e6e98829a62&client_secret=Lswl~Q~CXKOAV~xV3PDmC_1_44sj060S7T&grant_type=refresh_token&refresh_token=0.AAAActKf8nescEWdMLpYaf6YcgdEg0N74pZBk8IObpiCmmJ1AGs.AgABAAAAAAB2UyzwtQEKR7-rWbgdcBZIAQDs_wIA9P8N92raIi1UOQ895yBHkL_QcBF-Mw8kuSWnPDOkouf6Pr7ZMMQNd_4MQXFfuNtD_hU_MksXPxcgDXiOdFXvs4ylLLBY2hRE_--cSaiYwSWb_QNFnqFjo92AmPy1_ZsdVHpZWAP8Zq5f4Q7IWgQfMSMIbS5lqQHehtP005KIOH8WyXnrkHd9XJjI0H-ZNW3CcXt3-deUnxmG1qJNwkIVpRMv6fRjO0L3tUKPPs9xT_BXx2RJnQ8G_3Du-Zzd6-gxqG2vidtTg78gr3WeA_snhLQNIEhLNuM9SyLdlUgnazVhIq-oKPdzU2Hhmkrh4KqDdTpp92zq7WmnP2ek4-Cr37zjc2Wz7Lc7e31-tnz8EgNTICaHRdgw5OBnauiwPIkHeKdQHRqFPF2am_V64RAFXqqWbubb11YwPTpS_8M49FMCh_Rym0OvrMwids9eDYvvNmrJf151cQ5M2ZWg7SQUzQrhT8D6YsCgRCFwR2JXZYBuCLE1LZPzxRRLkTllQCUU5CcPHC6rlGTJhL4FzSlTCzDScUFA8jpQB1KBLXsxOX2Ue5Cgp24qyEXiIizmGsLASfetG_Aqqmn03ZEfAPd6paYXqGXOZdnk6TLn9QleeWwfSuEIC8N3soW3oDAfbRV5fkzEIW9IoGVcA4CoJavHuGrbNgmDzuTIXF-b9sWT8zAXGfBW1FiFmYifI0tImHv08EaxLw478yn3WE1rQaVXxdZMdoJpLz59BmfshyTBF_0-cGhLZY84U0I5m7IC
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: TokenStore::Refresh: code=400, response={"error":"invalid_request","error_description":"AADSTS90002: Tenant 'f29fd272-ac77-4570-9d30-ba5869fe9872' not found. This may happen if there are no active subscriptions for the tenant. Check to make sure you have the correct tenant ID. Check with your subscription administrator.\r\nTrace ID: 8c4dab53-f73f-494b-851e-ec008e568401\r\nCorrelation ID: a825e633-03fa-4df6-8155-26a2fe16ba96\r\nTimestamp: 2020-11-09 18:37:24Z","error_codes":[90002],"timestamp":"2020-11-09 18:37:24Z","trace_id":"8c4dab53-f73f-494b-851e-ec008e568401","correlation_id":"a825e633-03fa-4df6-8155-26a2fe16ba96","error_uri":"https://login.microsoftonline.com/error?code=90002"}
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: TokenStore::Refresh: request failed
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: Client::DoStep: new state 0 and err -5
Nov  9 13:37:24 localhost sasl-xoauth2[11438]:  2020-11-09 13:37:24: Client: destroyed
Nov  9 13:37:24 localhost sasl-xoauth2[11440]: auth failed:


But when I change the endpoint back to https://login.microsoftonline.com/common/oauth2/token I don't get any messages in the log from sasl-xoauth2.

2020-11-17 11:03 UTC, AntonyStellar commented
Hi guys,

I am a software developer who has found great use in this plugin. My colleagues and I are watching this pull request with great interest - we very much need the functionality you are working on. Are you happy for us to contribute, assuming we can fix the issues you are having?

Regards,

Antony

2020-11-17 15:01 UTC, karlrez commented
Hi Antony, 

I did manage to get this working, it turned out to be an issue with the way I was getting my initial access token. The developer included a script for this at /sasl-xoauth2/scripts and it solved the issue I was having.

Run: `python3 get-initial-outlook-tokens.py --client_id=exampleClientID tokens`
then follow the prompts and you should receive your token.

2020-11-17 15:34 UTC, AntonyStellar commented
Hi Karl,

Thank you very much for this :)

Antony

On Tue, 17 Nov 2020 at 15:01, Karl Rezansoff <notifications@github.com>
wrote:

> Hi Antony,
>
> I did manage to get this working, it turned out to be an issue with the
> way I was getting my initial access token. The developer included a script
> for this at /sasl-xoauth2/scripts and it solved the issue I was having.
>
> Run: python3 get-initial-outlook-tokens.py --client_id=exampleClientID
> tokens
> then follow the prompts and you should receive your token.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/tarickb/sasl-xoauth2/pull/5#issuecomment-728985965>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARZEMFQUFPBV2A4Q25EAVYDSQKF5JANCNFSM4SY6ZKFQ>
> .
>

2020-11-22 22:27 UTC, tarickb requested changes
Before merging these changes, could I trouble you to undo the README.md changes and remove the binary (sasl-xoauth2-0.9-CentOS7.tar.gz)? I've already got a bunch of README changes written up.

2020-11-23 14:52 UTC, tparkercbn commented
Good morning.

No problem. Let me make those changes.

Tom

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: tarickb <notifications@github.com>
Sent: Sunday, November 22, 2020 4:27:35 PM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


@tarickb requested changes on this pull request.

Before merging these changes, could I trouble you to undo the README.md changes and remove the binary (sasl-xoauth2-0.9-CentOS7.tar.gz)? I've already got a bunch of README changes written up.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#pullrequestreview-536122270>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5SQFAI7JCB677GO3NLSRGF5PANCNFSM4SY6ZKFQ>.

2020-11-23 17:53 UTC, tparkercbn commented
Can we close this PR without losing the history?

2020-11-23 17:53 UTC, closed without merging

2020-11-23 17:54 UTC, tparkercbn commented
I think that looks good.   I made a mess with the rebase so I created a new PR.

Tom

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
From: tarickb <notifications@github.com>
Sent: Sunday, November 22, 2020 4:27:35 PM
To: tarickb/sasl-xoauth2 <sasl-xoauth2@noreply.github.com>
Cc: Tom Parker <tparker@cbnco.com>; Author <author@noreply.github.com>
Subject: Re: [tarickb/sasl-xoauth2] Created a token_endpoint variable in the config file (#5)


@tarickb requested changes on this pull request.

Before merging these changes, could I trouble you to undo the README.md changes and remove the binary (sasl-xoauth2-0.9-CentOS7.tar.gz)? I've already got a bunch of README changes written up.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://github.com/tarickb/sasl-xoauth2/pull/5#pullrequestreview-536122270>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/ABJYF5SQFAI7JCB677GO3NLSRGF5PANCNFSM4SY6ZKFQ>.